import Tests.ParserTest
import Tests.LogicTest
import Tests.TranslatorTest
import Tests.SyntaxTest
import Tests.WorldDefsTest
import Tests.EvalOptTest
import Tests.CountTest
import Tests.LexorderTest
import Tests.TermOrderTest
import Tests.DriverTests
import Tests.PatternPins
import Tests.TamperTests
import Tests.SpikeTauOmega
