import Tests.ParserTest
import Tests.LogicTest
import Tests.TranslatorTest
import Tests.SyntaxTest
import Tests.WorldDefsTest
import Tests.EvalOptTest
import Tests.CountTest
import Tests.LexorderTest
import Tests.TermOrderTest
import Tests.DriverTests
import Tests.PatternPins
import Tests.SortingPins
import Tests.SortingPinsEndgame
import Tests.ParametricPins
import Tests.WaypointCensus
import Tests.MirrorNameCheck
import Tests.TamperTests
import Tests.SpikeTauOmega
