import ACL2Lean.Demo.Sorting.TCB
import ACL2Lean.Demo.Sorting.AclSource
import ACL2Lean.Imported.Perm
import ACL2Lean.Imported.ExecGen
import ACL2Lean.Imported.SimGen

/-! # The sorting books — LAYER 2 of 4: THE CORRESPONDENCE (`Iso`)

The bridge between an ACL2 PROGRAM and its `Sims` reading, in two
stages per function:

* **Stage 1, `*_exec_corr`** — a call of the ACL2 defun converges (in
  the `evalOpt` interpreter, at any world carrying that defun's body)
  to a total Lean `*Exec` function. Generated by `derive_exec%` where
  the recursion is on the template; hand-written where the measure is
  not (`msortExec`, `qsortExec`, `bnextExec`, `oLtExec`).
* **Stage 2, `*Exec_enc`** — that exec, applied to ENCODED inputs,
  computes the `Sims` native reading. Generated by `derive_sim%`.

This layer knows about the evaluator; it does NOT know about proof
logs or the replay driver. Nothing here asserts a relation BETWEEN two
different ACL2 functions — that is the mirror criterion's "ornamental
import" ban, and such facts may only arrive through a replayed
statement (see `Decode.lean`).

The DEFINITIONS on both sides come from the demo folder — the native
readings from `Demo/Sorting/TCB.lean`, the ACL2 bodies/symbols from
`Demo/Sorting/AclSource.lean`. Machinery imports the demo layer; the
demo layer never imports machinery (`scripts/check-trust-imports.sh`).

Split note: the ordinal/`acl2-count` half of this layer lives in
`IsoAdmission.lean` purely to respect the 1500-line module norm.
-/

open ACL2 ACL2.Replay ACL2.Lifting ACL2.Worlds.Perm ACL2.ExecGen

namespace ACL2.Worlds.Sorting

/-! ## Elementary facts about the TCB definitions

(The definitions themselves are `Demo/Sorting/TCB.lean`; these are the
first lemmas ABOUT them, used by the correspondences below.) -/

theorem lexorder_t_or_nil (x y : SExpr) :
    lexorder x y = SExpr.t ∨ lexorder x y = SExpr.nil := by
  fun_induction lexorder x y <;> first | assumption | simp

/-- The chain2 fold IS Mathlib's `List.IsChain` — the fully idiomatic
    reading of the ORDEREDP-shaped recognizers. -/
theorem chain2Rec_iff_isChain (p : SExpr → SExpr → Bool) :
    ∀ xs : List SExpr,
      chain2Rec p xs = true ↔ xs.IsChain (fun a b => p a b = true)
  | [] => by simp [chain2Rec]
  | [_] => by simp [chain2Rec]
  | a :: b :: t => by
    rw [show chain2Rec p (a :: b :: t)
          = (p a b && chain2Rec p (b :: t)) from rfl,
        Bool.and_eq_true, chain2Rec_iff_isChain p (b :: t),
        List.isChain_cons_cons]

/-! ## The concrete comparison modes (native vocabulary for the FILTER
rows: the quoted mode symbols specialize `relL` to plain `lexorderB`
combinations). -/

theorem relL_LT (a e : SExpr) : relL (symV "LT") a e = lexLtB a e := by
  rw [relL, if_pos (by decide)]; rfl

theorem relL_LTE (a e : SExpr) : relL (symV "LTE") a e = lexorderB a e := by
  rw [relL, if_neg (by decide), if_pos (by decide)]

theorem relL_GTE (a e : SExpr) : relL (symV "GTE") a e = lexorderB e a := by
  rw [relL, if_neg (by decide), if_neg (by decide), if_neg (by decide)]

theorem lexorder_eq_boolEnc (x y : SExpr) :
    lexorder x y = boolEnc (lexorderB x y) := by
  unfold lexorderB
  rcases lexorder_t_or_nil x y with h | h <;> rw [h] <;> decide

/-- LEXORDER as a `corr_chain2_enc`-shaped comparison: the builtin call
    computes `boolEnc (lexorderB a b)`. -/
theorem callBuiltin_lexorder_boolEnc (a b : SExpr) :
    callBuiltin "LEXORDER" [a, b] = some (boolEnc (lexorderB a b)) := by
  show some (lexorder a b) = some (boolEnc (lexorderB a b))
  rw [lexorder_eq_boolEnc]

/-- `orderedp` over an encoded argument computes `orderedpRec` — the
    chain2 schematic at `cmp = LEXORDER`. The h_fn body IS the sorting
    books' ORDEREDP verbatim (`chain2Body "LEXORDER" "ORDEREDP"`). -/
theorem corr_orderedp_enc (w : World)
    (h_fn : w.defs.get? { package := "ACL2", name := "ORDEREDP" }
      = some ([{ package := "ACL2", name := "X" }],
              chain2Body "LEXORDER" "ORDEREDP"))
    (h_no_consp : w.defs.get? ({ name := "CONSP" } : Symbol) = none)
    (h_no_cdr : w.defs.get? ({ name := "CDR" } : Symbol) = none)
    (h_no_car : w.defs.get? ({ name := "CAR" } : Symbol) = none)
    (h_no_lexorder : w.defs.get? ({ name := "LEXORDER" } : Symbol) = none) :
    ∀ (xs : List SExpr) (e' : Env) (a : SExpr),
    (∃ N, ∀ f ≥ N, evalOpt f w e' a = some (enc xs)) →
    ∃ N, ∀ f ≥ N, evalOpt f w e' (orderedpT a)
      = some (boolEnc (orderedpRec xs)) :=
  corr_chain2_enc w "LEXORDER" "ORDEREDP" lexorderB (by decide) (by decide)
    h_fn h_no_consp h_no_cdr h_no_car h_no_lexorder
    callBuiltin_lexorder_boolEnc

/-- `car` of an encoded list is `headD nil` — the native reading of CAR on
    the list fragment. -/
theorem car_enc (l : List SExpr) : Logic.car (enc l) = l.headD SExpr.nil := by
  cases l <;> rfl

theorem callBuiltin_lexorder (a b : SExpr) :
    callBuiltin "LEXORDER" [a, b] = some (lexorder a b) := rfl

/-- `insert`'s body as a total Lean function (shape-exact, D2) —
    GENERATED (1b retirement: the hand def this replaces is reproduced
    by the generator's body walk; every downstream consumer, starting
    with the hand `insert_exec_corr`, re-elaborates against it). -/
derive_exec% insertExec corr insert_exec_corr for insert_sym
  formals [eS, xS] body insertBody measured 1

private theorem toBool_lexorder (e a : SExpr) :
    Logic.toBool (lexorder e a) = lexorderB e a := by
  rw [lexorder_eq_boolEnc]; cases lexorderB e a <;> rfl

/-- Stage 2: `insertExec` on an encoded list computes `insertL` —
    GENERATED (`derive_sim%`, charter item 2): the iso is proved by the
    fixed template off `insertL`'s own recursion. -/
derive_sim% insertExec_enc for "INSERT"
  vars (e : raw) (xs : list)
  exec [e, xs]
  native (enc (insertL e xs))
  simp [insertL, lexorder_eq_boolEnc]
  induct functional (insertL e xs)

/-- `isort`'s body as a total Lean function — GENERATED (the INSERT call
    resolves through the kit registry). -/
derive_exec% isortExec corr isort_exec_corr for isort_sym
  formals [xS] body isortBody measured 0

/-- Stage 2: `isortExec` on an encoded list computes `isortL` —
    GENERATED; the INSERT callee iso resolves through the kit registry. -/
derive_sim% isortExec_enc for "ISORT"
  vars (xs : list)
  exec [xs]
  native (enc (isortL xs))
  simp [isortL]
  induct functional (isortL xs)

/-- `isort` over an encoded argument computes `isortL` under `enc`. -/
theorem corr_isort_enc (w : World)
    (h_insert : w.defs.get? insert_sym = some ([eS, xS], insertBody))
    (h_isort : w.defs.get? isort_sym = some ([xS], isortBody))
    (h_no_consp : w.defs.get? ({ name := "CONSP" } : Symbol) = none)
    (h_no_car : w.defs.get? ({ name := "CAR" } : Symbol) = none)
    (h_no_cdr : w.defs.get? ({ name := "CDR" } : Symbol) = none)
    (h_no_cons : w.defs.get? ({ name := "CONS" } : Symbol) = none)
    (h_no_lexorder : w.defs.get? ({ name := "LEXORDER" } : Symbol) = none) :
    ∀ (xs : List SExpr) (e' : Env) (x : SExpr),
    (∃ N, ∀ f ≥ N, evalOpt f w e' x = some (enc xs)) →
    ∃ N, ∀ f ≥ N, evalOpt f w e' (isortT x) = some (enc (isortL xs)) := by
  intro xs e' x hx
  have h := isort_exec_corr w h_insert h_isort h_no_consp h_no_car h_no_cdr
    h_no_cons h_no_lexorder e' x (enc xs) hx
  rwa [isortExec_enc] at h

/-- Any variable converges in any env (unbound reads nil; none of the
    rule variables is `T`). -/
theorem conv_var (w : World) (env' : Env) (s : Symbol)
    (h : s.isNamed "T" = false) :
    ∃ v, ∃ N, ∀ f ≥ N, evalOpt f w env' (.atom (.symbol s)) = some v :=
  ⟨_, re_val_var w env' s h⟩

theorem conv_plusT (w : World) (env' : Env) (a b av bv : SExpr)
    (h_no_plus : w.defs.get? ({ name := "BINARY-+" } : Symbol) = none)
    (ha : ∃ N, ∀ f ≥ N, evalOpt f w env' a = some av)
    (hb : ∃ N, ∀ f ≥ N, evalOpt f w env' b = some bv) :
    ∃ N, ∀ f ≥ N, evalOpt f w env' (plusT a b)
      = some (Logic.plus av bv) :=
  conv_builtin2 w env' { name := "BINARY-+" } a b av bv _ (by decide)
    h_no_plus ha hb (callBuiltin_plus _ _)

/-- `how-many`'s body as a total Lean function. -/
derive_exec% howManyExec corr how_many_exec_corr for how_many_sym
  formals [eS, xS] body howManyBody measured 1

/-- Stage 2: `howManyExec` on an encoded list computes `List.count`
    (as an SExpr integer) — GENERATED; the result reading is the `intRep`
    reading (an SExpr integer atom). -/
derive_sim% howManyExec_enc for "HOW-MANY"
  vars (e : raw) (xs : list)
  exec [e, xs]
  native (SExpr.atom (.number (.int (xs.count e))))
  simp [Logic.plus, Logic.toRat, Logic.mkNumber, List.count_cons]
  induct structural xs

/-- `rel`'s body as a total Lean function (non-recursive dispatch). -/
derive_exec% relExec corr rel_exec_corr for rel_sym
  formals [fnS, iS, jS] body relBody

theorem relExec_t_or_nil (f i j : SExpr) :
    relExec f i j = SExpr.t ∨ relExec f i j = SExpr.nil := by
  unfold relExec
  repeat' split
  all_goals first
    | exact Or.inl rfl
    | exact Or.inr rfl
    | exact lexorder_t_or_nil _ _

/-- `all-rel`'s body as a total Lean function. -/
derive_exec% allRelExec corr all_rel_exec_corr for all_rel_sym
  formals [fnS, xS, eS] body allRelBody measured 1

private theorem toBool_strict (x y a e : SExpr) :
    Logic.toBool
      (if Logic.toBool (lexorder x y) = true then
        (if Logic.toBool (Logic.equal a e) = true then SExpr.nil
         else SExpr.t)
       else SExpr.nil)
      = (lexorderB x y && !(a == e)) := by
  rw [toBool_lexorder, toBool_equal]
  cases hl : lexorderB x y <;> cases he : a == e <;>
    simp [Logic.toBool, SExpr.t]

/-- The exec dispatch computes exactly the native `relL` verdict. -/
theorem toBool_relExec (fv a e : SExpr) :
    Logic.toBool (relExec fv a e) = relL fv a e := by
  unfold relExec relL
  by_cases hLT : (fv == symV "LT") = true
  · rw [if_pos (by rw [toBool_equal]; exact hLT), if_pos hLT]
    exact toBool_strict a e a e
  · rw [if_neg (by rw [toBool_equal]; exact hLT), if_neg hLT]
    by_cases hLTE : (fv == symV "LTE") = true
    · rw [if_pos (by rw [toBool_equal]; exact hLTE), if_pos hLTE]
      exact toBool_lexorder a e
    · rw [if_neg (by rw [toBool_equal]; exact hLTE), if_neg hLTE]
      by_cases hGT : (fv == symV "GT") = true
      · rw [if_pos (by rw [toBool_equal]; exact hGT), if_pos hGT]
        exact toBool_strict e a a e
      · rw [if_neg (by rw [toBool_equal]; exact hGT), if_neg hGT]
        exact toBool_lexorder e a

/-- Stage 2: `allRelExec` on an encoded list computes `allRelL` —
    GENERATED; the REL dispatch has no iso of its own, so its `toBool`
    bridge is declared. -/
derive_sim% allRelExec_enc for "ALL-REL"
  vars (fv : raw) (ev : raw) (xs : list)
  exec [fv, xs, ev]
  native (boolEnc (allRelL fv ev xs))
  simp [allRelL, toBool_relExec]
  induct structural xs

/-- `allRelExec` is two-valued. -/
theorem allRelExec_t_or_nil (fv x ev : SExpr) :
    allRelExec fv x ev = SExpr.t ∨ allRelExec fv x ev = SExpr.nil := by
  fun_induction allRelExec fv x ev with
  | case1 x _ _ ih => exact ih
  | case2 x _ _ => exact Or.inr rfl
  | case3 x _ => exact Or.inl rfl

/-- `filter`'s body as a total Lean function. -/
derive_exec% filterExec corr filter_exec_corr for filter_sym
  formals [fnS, xS, eS] body filterBody measured 1

/-- Stage 2: `filterExec` on an encoded list computes `filterL` —
    GENERATED. -/
derive_sim% filterExec_enc for "FILTER"
  vars (fv : raw) (ev : raw) (xs : list)
  exec [fv, xs, ev]
  native (enc (filterL fv ev xs))
  simp [filterL, toBool_relExec]
  induct structural xs

private theorem append_ns :
    (append_sym.isNamed "QUOTE" = false ∧ append_sym.isNamed "IF" = false ∧
     append_sym.isNamed "LET" = false ∧
     append_sym.isNamed "LET*" = false) := by decide

theorem bindArgs_xy_x' (vx vy : SExpr) :
    (bindArgs [xS, yS] [vx, vy]).get? xS = some vx := by
  show ((({} : Env).insert yS vy).insert xS vx).get? xS = some vx
  rw [Env.get?_insert, if_pos (by decide)]

theorem bindArgs_xy_y' (vx vy : SExpr) :
    (bindArgs [xS, yS] [vx, vy]).get? yS = some vy := by
  show ((({} : Env).insert yS vy).insert xS vx).get? yS = some vy
  rw [Env.get?_insert, if_neg (by decide), Env.get?_insert,
      if_pos (by decide)]

/-- `binary-append`'s body as a total Lean function (over ARBITRARY
    values — the enc-only `corr_append_enc` cannot serve the args-valued
    TP hypothesis). -/
def appendExec (x y : SExpr) : SExpr :=
  if Logic.toBool (Logic.consp x) = true then
    Logic.cons (Logic.car x) (appendExec (Logic.cdr x) y)
  else y
termination_by x.consCount
decreasing_by exact consCount_cdr_lt_of_consp (by assumption)

register_exec_kit% "BINARY-APPEND" => appendExec arity 2

/-- Stage 1: a `binary-append` call converges to `appendExec`. -/
theorem append_exec_corr (w : World)
    (h_app : w.defs.get? append_sym
      = some ([{ package := "ACL2", name := "X" },
               { package := "ACL2", name := "Y" }],
              appendBody "BINARY-APPEND"))
    (h_no_consp : w.defs.get? ({ name := "CONSP" } : Symbol) = none)
    (h_no_car : w.defs.get? ({ name := "CAR" } : Symbol) = none)
    (h_no_cdr : w.defs.get? ({ name := "CDR" } : Symbol) = none)
    (h_no_cons : w.defs.get? ({ name := "CONS" } : Symbol) = none) :
    ∀ (env : Env) (a b av bv : SExpr),
      ConvTo w env a av → ConvTo w env b bv →
      ConvTo w env (appendT a b) (appendExec av bv) := by
  have hbody : ∀ xv yv : SExpr,
      ConvTo w (bindArgs [xS, yS] [xv, yv]) (appendBody "BINARY-APPEND")
        (appendExec xv yv) := by
    refine consCount_strong_induction
      (fun xv => ∀ yv, ConvTo w (bindArgs [xS, yS] [xv, yv])
        (appendBody "BINARY-APPEND") (appendExec xv yv)) ?_
    intro xv ih yv
    have hxv := re_val_var_get w (bindArgs [xS, yS] [xv, yv])
      { name := "X" } xv (bindArgs_xy_x' xv yv)
    have hyv := re_val_var_get w (bindArgs [xS, yS] [xv, yv])
      { name := "Y" } yv (bindArgs_xy_y' xv yv)
    have hconsp := conv_builtin1 w _ { name := "CONSP" } xT xv
      (Logic.consp xv) (by decide) h_no_consp hxv (callBuiltin_consp _)
    have hcar := conv_builtin1 w _ { name := "CAR" } xT xv
      (Logic.car xv) (by decide) h_no_car hxv (callBuiltin_car _)
    have hcdr := conv_builtin1 w _ { name := "CDR" } xT xv
      (Logic.cdr xv) (by decide) h_no_cdr hxv (callBuiltin_cdr _)
    have houter := conv_if_lift w (bindArgs [xS, yS] [xv, yv]) (conspT xT)
      (consT (carT xT) (appendT (cdrT xT) yT)) yT (Logic.consp xv)
      (Logic.cons (Logic.car xv) (appendExec (Logic.cdr xv) yv)) yv hconsp
      (fun hb =>
        conv_builtin2 w _ { name := "CONS" } (carT xT)
          (appendT (cdrT xT) yT) (Logic.car xv)
          (appendExec (Logic.cdr xv) yv) _ (by decide) h_no_cons hcar
          (conv_defn_2 w _ append_sym (cdrT xT) yT (Logic.cdr xv) yv
            xS yS (appendBody "BINARY-APPEND") _ append_ns h_app hcdr hyv
            (ih (Logic.cdr xv) (consCount_cdr_lt_of_consp hb) yv))
          rfl)
      (fun _ => hyv)
    rw [appendExec.eq_def]
    exact houter
  intro env a b av bv ha hb
  exact conv_defn_2 w env append_sym a b av bv xS yS
    (appendBody "BINARY-APPEND") _ append_ns h_app ha hb (hbody av bv)

private theorem odds_ns :
    (odds_sym.isNamed "QUOTE" = false ∧ odds_sym.isNamed "IF" = false ∧
     odds_sym.isNamed "LET" = false ∧
     odds_sym.isNamed "LET*" = false) := by decide

private theorem msort_ns :
    (msort_sym.isNamed "QUOTE" = false ∧ msort_sym.isNamed "IF" = false ∧
     msort_sym.isNamed "LET" = false ∧
     msort_sym.isNamed "LET*" = false) := by decide

private theorem bindArgs_l_l (v : SExpr) :
    (bindArgs [lS] [v]).get? lS = some v :=
  bindArgs_single_get_self lS v

/-- `merge2`'s body as a total Lean function — GENERATED (M2: the emitted
    pair-sum measure `(+ (ACL2-COUNT X) (ACL2-COUNT Y))`; per-site
    single-CDR one-side decreases; corr by Nat strong induction over the
    sum). -/
derive_exec% merge2Exec corr merge2_exec_corr for merge2_sym
  formals [xS, yS] body merge2Body measured 0 1

/-- Stage 2: `merge2Exec` on encoded lists computes `merge2L` —
    GENERATED (a two-list reading; the native's own `length`-measure
    recursion drives the induction while the exec recurses on the
    `consCount` pair-sum). -/
derive_sim% merge2Exec_enc for "MERGE2"
  vars (xs : list) (ys : list)
  exec [xs, ys]
  native (enc (merge2L xs ys))
  simp [merge2L, lexorder_eq_boolEnc]
  induct functional (merge2L xs ys)

/-- `evens`'s body as a total Lean function. -/
derive_exec% evensExec corr evens_exec_corr for evens_sym
  formals [lS] body evensBody measured 0

/-- Stage 2: `evensExec` on an encoded list computes `evensL` —
    GENERATED (the T2 measure-change shape: the native recurses on
    `List.length`, the exec on `consCount`). -/
derive_sim% evensExec_enc for "EVENS"
  vars (xs : list)
  exec [xs]
  native (enc (evensL xs))
  simp [evensL]
  induct functional (evensL xs)

/-- `evensExec` never increases the count. -/
theorem evensExec_consCount_le (l : SExpr) :
    (evensExec l).consCount ≤ l.consCount := by
  fun_induction evensExec l with
  | case1 l hb ih =>
    cases l with
    | nil => simp [Logic.consp, Logic.toBool] at hb
    | atom _ => simp [Logic.consp, Logic.toBool] at hb
    | cons a d =>
      have hle : (Logic.cdr (Logic.cdr (SExpr.cons a d))).consCount
          ≤ d.consCount := by
        calc (Logic.cdr (Logic.cdr (SExpr.cons a d))).consCount
            = (Logic.cdr d).consCount := rfl
          _ ≤ d.consCount := consCount_cdr_le _
      simp only [Logic.cons, Logic.car, consCount_cons]
      omega
  | case2 l _ => simp

/-- `evensExec` strictly decreases the count on a two-or-more list. -/
theorem evensExec_consCount_lt {l : SExpr}
    (h1 : Logic.toBool (Logic.consp l) = true)
    (h2 : Logic.toBool (Logic.consp (Logic.cdr l)) = true) :
    (evensExec l).consCount < l.consCount := by
  cases l with
  | nil => simp [Logic.consp, Logic.toBool] at h1
  | atom _ => simp [Logic.consp, Logic.toBool] at h1
  | cons a d =>
    cases d with
    | nil => simp [Logic.cdr, Logic.consp, Logic.toBool] at h2
    | atom _ => simp [Logic.cdr, Logic.consp, Logic.toBool] at h2
    | cons b d' =>
      rw [evensExec.eq_def, if_pos h1,
          show Logic.cdr (Logic.cdr (SExpr.cons a (SExpr.cons b d'))) = d'
            from rfl,
          show Logic.car (SExpr.cons a (SExpr.cons b d')) = a from rfl]
      have hle := evensExec_consCount_le d'
      simp only [Logic.cons, consCount_cons]
      omega

/-- `msort`'s body as a total Lean function. -/
def msortExec (x : SExpr) : SExpr :=
  if _h1 : Logic.toBool (Logic.consp x) = true then
    if _h2 : Logic.toBool (Logic.consp (Logic.cdr x)) = true then
      merge2Exec (msortExec (evensExec x))
        (msortExec (evensExec (Logic.cdr x)))
    else Logic.cons (Logic.car x) SExpr.nil
  else SExpr.nil
termination_by x.consCount
decreasing_by
  · exact evensExec_consCount_lt _h1 _h2
  · calc (evensExec (Logic.cdr x)).consCount
        ≤ (Logic.cdr x).consCount := evensExec_consCount_le _
      _ < x.consCount := consCount_cdr_lt_of_consp _h1

register_exec_kit% "MSORT" => msortExec arity 1

/-- Stage 1: an `msort` call converges to `msortExec`. -/
theorem msort_exec_corr (w : World)
    (h_m2 : w.defs.get? merge2_sym = some ([xS, yS], merge2Body))
    (h_evens : w.defs.get? evens_sym = some ([lS], evensBody))
    (h_odds : w.defs.get? odds_sym = some ([lS], oddsBody))
    (h_msort : w.defs.get? msort_sym = some ([xS], msortBody))
    (h_no_consp : w.defs.get? ({ name := "CONSP" } : Symbol) = none)
    (h_no_car : w.defs.get? ({ name := "CAR" } : Symbol) = none)
    (h_no_cdr : w.defs.get? ({ name := "CDR" } : Symbol) = none)
    (h_no_cons : w.defs.get? ({ name := "CONS" } : Symbol) = none)
    (h_no_lexorder : w.defs.get? ({ name := "LEXORDER" } : Symbol) = none) :
    ∀ (env : Env) (x xv : SExpr),
      ConvTo w env x xv → ConvTo w env (msortT x) (msortExec xv) := by
  have hbody : ∀ xv : SExpr,
      ConvTo w (bindArgs [xS] [xv]) msortBody (msortExec xv) := by
    refine consCount_strong_induction
      (fun xv => ConvTo w (bindArgs [xS] [xv]) msortBody (msortExec xv)) ?_
    intro xv ih
    have hxv := re_val_var_get w (bindArgs [xS] [xv]) { name := "X" } xv
      (bindArgs_single_get_self xS xv)
    have hconsp := conv_builtin1 w _ { name := "CONSP" } xT xv
      (Logic.consp xv) (by decide) h_no_consp hxv (callBuiltin_consp _)
    have hcar := conv_builtin1 w _ { name := "CAR" } xT xv
      (Logic.car xv) (by decide) h_no_car hxv (callBuiltin_car _)
    have hcdr := conv_builtin1 w _ { name := "CDR" } xT xv
      (Logic.cdr xv) (by decide) h_no_cdr hxv (callBuiltin_cdr _)
    have hconsp2 := conv_builtin1 w _ { name := "CONSP" } (cdrT xT)
      (Logic.cdr xv) (Logic.consp (Logic.cdr xv)) (by decide) h_no_consp
      hcdr (callBuiltin_consp _)
    -- the two-element-plus branch, conditional on BOTH consp verdicts
    have hbig : Logic.toBool (Logic.consp xv) = true →
        Logic.toBool (Logic.consp (Logic.cdr xv)) = true →
        ConvTo w (bindArgs [xS] [xv])
          (merge2T (msortT (evensT xT)) (msortT (oddsT xT)))
          (merge2Exec (msortExec (evensExec xv))
            (msortExec (evensExec (Logic.cdr xv)))) := by
      intro hb1 hb2
      have hevens := evens_exec_corr w h_evens h_no_consp h_no_car
        h_no_cdr h_no_cons _ xT xv hxv
      have hodds : ConvTo w (bindArgs [xS] [xv]) (oddsT xT)
          (evensExec (Logic.cdr xv)) := by
        refine conv_defn_1 w _ odds_sym xT xv lS oddsBody _
          odds_ns h_odds hxv ?_
        -- odds' body walk: (EVENS (CDR L)) at l ↦ xv
        have hl := re_val_var_get w (bindArgs [lS] [xv]) { name := "L" }
          xv (bindArgs_l_l xv)
        have hcdrl := conv_builtin1 w _ { name := "CDR" } lT xv
          (Logic.cdr xv) (by decide) h_no_cdr hl (callBuiltin_cdr _)
        exact evens_exec_corr w h_evens h_no_consp h_no_car h_no_cdr
          h_no_cons _ (cdrT lT) (Logic.cdr xv) hcdrl
      have hmsE := conv_defn_1 w _ msort_sym (evensT xT) (evensExec xv)
        xS msortBody _ msort_ns h_msort hevens
        (ih (evensExec xv) (evensExec_consCount_lt hb1 hb2))
      have hmsO := conv_defn_1 w _ msort_sym (oddsT xT)
        (evensExec (Logic.cdr xv)) xS msortBody _ msort_ns h_msort hodds
        (ih (evensExec (Logic.cdr xv))
          (lt_of_le_of_lt (evensExec_consCount_le _)
            (consCount_cdr_lt_of_consp hb1)))
      exact merge2_exec_corr w h_m2 h_no_consp h_no_car h_no_cdr h_no_cons
        h_no_lexorder _ (msortT (evensT xT)) (msortT (oddsT xT))
        (msortExec (evensExec xv)) (msortExec (evensExec (Logic.cdr xv)))
        hmsE hmsO
    have houter := conv_if_lift w (bindArgs [xS] [xv]) (conspT xT)
      (ifT (conspT (cdrT xT))
        (merge2T (msortT (evensT xT)) (msortT (oddsT xT)))
        (consT (carT xT) qNil))
      qNil (Logic.consp xv)
      (if Logic.toBool (Logic.consp (Logic.cdr xv)) = true then
        merge2Exec (msortExec (evensExec xv))
          (msortExec (evensExec (Logic.cdr xv)))
       else Logic.cons (Logic.car xv) SExpr.nil)
      SExpr.nil hconsp
      (fun hb1 =>
        conv_if_lift w _ (conspT (cdrT xT))
          (merge2T (msortT (evensT xT)) (msortT (oddsT xT)))
          (consT (carT xT) qNil) (Logic.consp (Logic.cdr xv))
          (merge2Exec (msortExec (evensExec xv))
            (msortExec (evensExec (Logic.cdr xv))))
          (Logic.cons (Logic.car xv) SExpr.nil) hconsp2
          (fun hb2 => hbig hb1 hb2)
          (fun _ =>
            conv_builtin2 w _ { name := "CONS" } (carT xT) qNil
              (Logic.car xv) SExpr.nil _ (by decide) h_no_cons hcar
              (re_val_quote w _ SExpr.nil) rfl))
      (fun _ => re_val_quote w _ SExpr.nil)
    rw [msortExec.eq_def]
    -- the exec's dite matches the walk's ite branch values
    simp only [dite_eq_ite] at *
    exact houter
  intro env x xv hx
  exact conv_defn_1 w env msort_sym x xv xS msortBody _
    msort_ns h_msort hx (hbody xv)

/-- Stage 2: `msortExec` on an encoded list computes `msortL` —
    GENERATED (the exec is hand-written, an M3 measure beyond
    `derive_exec%`, but its ISO is on the template: the EVENS/MERGE2
    callee isos resolve through the kit registry). -/
derive_sim% msortExec_enc for "MSORT"
  vars (xs : list)
  exec [xs]
  native (enc (msortL xs))
  simp [msortL]
  induct functional (msortL xs)

private theorem qsort_ns :
    (qsort_sym.isNamed "QUOTE" = false ∧ qsort_sym.isNamed "IF" = false ∧
     qsort_sym.isNamed "LET" = false ∧
     qsort_sym.isNamed "LET*" = false) := by decide

/-- `filterExec` never increases the count. -/
theorem filterExec_consCount_le (fv x ev : SExpr) :
    (filterExec fv x ev).consCount ≤ x.consCount := by
  fun_induction filterExec fv x ev with
  | case1 x hc _ ih =>
    cases x with
    | nil => simp [Logic.consp, Logic.toBool] at hc
    | atom _ => simp [Logic.consp, Logic.toBool] at hc
    | cons a d =>
      rw [show Logic.cdr (SExpr.cons a d) = d from rfl] at ih
      simp only [Logic.cons, Logic.car, Logic.cdr, consCount_cons]
      omega
  | case2 x hc _ ih =>
    exact le_trans ih (consCount_cdr_le _)
  | case3 x _ => simp

def qsortExec (x : SExpr) : SExpr :=
  if _h1 : Logic.toBool (Logic.consp x) = true then
    if Logic.toBool (Logic.consp (Logic.cdr x)) = true then
      appendExec
        (qsortExec (filterExec (symV "LT") (Logic.cdr x) (Logic.car x)))
        (Logic.cons (Logic.car x)
          (qsortExec (filterExec (symV "GTE") (Logic.cdr x) (Logic.car x))))
    else Logic.cons (Logic.car x) SExpr.nil
  else SExpr.nil
termination_by x.consCount
decreasing_by
  · exact lt_of_le_of_lt (filterExec_consCount_le _ _ _)
      (consCount_cdr_lt_of_consp _h1)
  · exact lt_of_le_of_lt (filterExec_consCount_le _ _ _)
      (consCount_cdr_lt_of_consp _h1)

register_exec_kit% "QSORT" => qsortExec arity 1

/-- Stage 1: a `qsort` call converges to `qsortExec`. -/
theorem qsort_exec_corr (w : World)
    (h_qs : w.defs.get? qsort_sym = some ([xS], qsortBody))
    (h_rel : w.defs.get? rel_sym = some ([fnS, iS, jS], relBody))
    (h_filter : w.defs.get? filter_sym = some ([fnS, xS, eS], filterBody))
    (h_app : w.defs.get? append_sym
      = some ([{ package := "ACL2", name := "X" },
               { package := "ACL2", name := "Y" }],
              appendBody "BINARY-APPEND"))
    (h_no_consp : w.defs.get? ({ name := "CONSP" } : Symbol) = none)
    (h_no_equal : w.defs.get? ({ name := "EQUAL" } : Symbol) = none)
    (h_no_car : w.defs.get? ({ name := "CAR" } : Symbol) = none)
    (h_no_cdr : w.defs.get? ({ name := "CDR" } : Symbol) = none)
    (h_no_cons : w.defs.get? ({ name := "CONS" } : Symbol) = none)
    (h_no_lexorder : w.defs.get? ({ name := "LEXORDER" } : Symbol) = none) :
    ∀ (env : Env) (x xv : SExpr),
      ConvTo w env x xv → ConvTo w env (qsortT x) (qsortExec xv) := by
  have hbody : ∀ xv : SExpr,
      ConvTo w (bindArgs [xS] [xv]) qsortBody (qsortExec xv) := by
    refine consCount_strong_induction
      (fun xv => ConvTo w (bindArgs [xS] [xv]) qsortBody (qsortExec xv)) ?_
    intro xv ih
    have hxv := re_val_var_get w (bindArgs [xS] [xv]) { name := "X" } xv
      (bindArgs_single_get_self xS xv)
    have hconsp := conv_builtin1 w _ { name := "CONSP" } xT xv
      (Logic.consp xv) (by decide) h_no_consp hxv (callBuiltin_consp _)
    have hcar := conv_builtin1 w _ { name := "CAR" } xT xv
      (Logic.car xv) (by decide) h_no_car hxv (callBuiltin_car _)
    have hcdr := conv_builtin1 w _ { name := "CDR" } xT xv
      (Logic.cdr xv) (by decide) h_no_cdr hxv (callBuiltin_cdr _)
    have hconsp2 := conv_builtin1 w _ { name := "CONSP" } (cdrT xT)
      (Logic.cdr xv) (Logic.consp (Logic.cdr xv)) (by decide) h_no_consp
      hcdr (callBuiltin_consp _)
    have hfilLT := filter_exec_corr w h_rel h_filter h_no_consp h_no_equal
      h_no_car h_no_cdr h_no_cons h_no_lexorder _ (qSym "LT") (cdrT xT)
      (carT xT) (symV "LT") (Logic.cdr xv) (Logic.car xv)
      (re_val_quote w _ (symV "LT")) hcdr hcar
    have hfilGTE := filter_exec_corr w h_rel h_filter h_no_consp h_no_equal
      h_no_car h_no_cdr h_no_cons h_no_lexorder _ (qSym "GTE") (cdrT xT)
      (carT xT) (symV "GTE") (Logic.cdr xv) (Logic.car xv)
      (re_val_quote w _ (symV "GTE")) hcdr hcar
    have hbig : Logic.toBool (Logic.consp xv) = true →
        ConvTo w (bindArgs [xS] [xv])
          (appendT
            (qsortT (filterT (qSym "LT") (cdrT xT) (carT xT)))
            (consT (carT xT)
              (qsortT (filterT (qSym "GTE") (cdrT xT) (carT xT)))))
          (appendExec
            (qsortExec (filterExec (symV "LT") (Logic.cdr xv)
              (Logic.car xv)))
            (Logic.cons (Logic.car xv)
              (qsortExec (filterExec (symV "GTE") (Logic.cdr xv)
                (Logic.car xv))))) := by
      intro hb1
      have hlt : (filterExec (symV "LT") (Logic.cdr xv)
          (Logic.car xv)).consCount < xv.consCount :=
        lt_of_le_of_lt (filterExec_consCount_le _ _ _)
          (consCount_cdr_lt_of_consp hb1)
      have hgte : (filterExec (symV "GTE") (Logic.cdr xv)
          (Logic.car xv)).consCount < xv.consCount :=
        lt_of_le_of_lt (filterExec_consCount_le _ _ _)
          (consCount_cdr_lt_of_consp hb1)
      have hqsLT := conv_defn_1 w _ qsort_sym
        (filterT (qSym "LT") (cdrT xT) (carT xT))
        (filterExec (symV "LT") (Logic.cdr xv) (Logic.car xv))
        xS qsortBody _ qsort_ns h_qs hfilLT
        (ih _ hlt)
      have hqsGTE := conv_defn_1 w _ qsort_sym
        (filterT (qSym "GTE") (cdrT xT) (carT xT))
        (filterExec (symV "GTE") (Logic.cdr xv) (Logic.car xv))
        xS qsortBody _ qsort_ns h_qs hfilGTE
        (ih _ hgte)
      have hcons2 := conv_builtin2 w _ { name := "CONS" } (carT xT)
        (qsortT (filterT (qSym "GTE") (cdrT xT) (carT xT)))
        (Logic.car xv) _ _ (by decide) h_no_cons hcar hqsGTE rfl
      exact append_exec_corr w h_app h_no_consp h_no_car h_no_cdr
        h_no_cons _ _ _ _ _ hqsLT hcons2
    have houter := conv_if_lift w (bindArgs [xS] [xv]) (conspT xT)
      (ifT (conspT (cdrT xT))
        (appendT
          (qsortT (filterT (qSym "LT") (cdrT xT) (carT xT)))
          (consT (carT xT)
            (qsortT (filterT (qSym "GTE") (cdrT xT) (carT xT)))))
        (consT (carT xT) qNil))
      qNil (Logic.consp xv)
      (if Logic.toBool (Logic.consp (Logic.cdr xv)) = true then
        appendExec
          (qsortExec (filterExec (symV "LT") (Logic.cdr xv) (Logic.car xv)))
          (Logic.cons (Logic.car xv)
            (qsortExec (filterExec (symV "GTE") (Logic.cdr xv)
              (Logic.car xv))))
       else Logic.cons (Logic.car xv) SExpr.nil)
      SExpr.nil hconsp
      (fun hb1 =>
        conv_if_lift w _ (conspT (cdrT xT)) _ (consT (carT xT) qNil)
          (Logic.consp (Logic.cdr xv))
          (appendExec
            (qsortExec (filterExec (symV "LT") (Logic.cdr xv)
              (Logic.car xv)))
            (Logic.cons (Logic.car xv)
              (qsortExec (filterExec (symV "GTE") (Logic.cdr xv)
                (Logic.car xv)))))
          (Logic.cons (Logic.car xv) SExpr.nil) hconsp2
          (fun _ => hbig hb1)
          (fun _ =>
            conv_builtin2 w _ { name := "CONS" } (carT xT) qNil
              (Logic.car xv) SExpr.nil _ (by decide) h_no_cons hcar
              (re_val_quote w _ SExpr.nil) rfl))
      (fun _ => re_val_quote w _ SExpr.nil)
    rw [qsortExec.eq_def]
    simp only [dite_eq_ite]
    exact houter
  intro env x xv hx
  exact conv_defn_1 w env qsort_sym x xv xS qsortBody _
    qsort_ns h_qs hx (hbody xv)

/-- Pure append on encodings (the world-free twin of `corr_append_enc`)
    — GENERATED. -/
derive_sim% appendExec_enc for "BINARY-APPEND"
  vars (xs : list) (ys : list)
  exec [xs, ys]
  native (enc (xs ++ ys))
  simp []
  induct structural xs

/-- Stage 2: `qsortExec` on an encoded list computes `qsortL` —
    GENERATED (hand exec, M3 measure; the FILTER/BINARY-APPEND callee
    isos resolve through the kit registry). -/
derive_sim% qsortExec_enc for "QSORT"
  vars (xs : list)
  exec [xs]
  native (enc (qsortL xs))
  simp [qsortL, filterL]
  induct functional (qsortL xs)

private theorem pce_ns :
    (pce_sym.isNamed "QUOTE" = false ∧ pce_sym.isNamed "IF" = false ∧
     pce_sym.isNamed "LET" = false ∧ pce_sym.isNamed "LET*" = false) := by
  decide

/-- `perm-counter-example`'s body as a total Lean function. -/
def pceExec (x y : SExpr) : SExpr :=
  if Logic.toBool (Logic.consp x) = true then
    if Logic.toBool (membExec (Logic.car x) y) = true then
      pceExec (Logic.cdr x) (rmExec (Logic.car x) y)
    else Logic.car x
  else Logic.car y
termination_by x.consCount
decreasing_by exact consCount_cdr_lt_of_consp (by assumption)

/-- Stage 1: a `perm-counter-example` call converges to `pceExec`. -/
theorem pce_exec_corr (w : World)
    (h_pce : w.defs.get? pce_sym = some ([xS, yS], pceBody))
    (h_memb : w.defs.get? { package := "ACL2", name := "MEMB" }
      = some ([{ package := "ACL2", name := "A" },
               { package := "ACL2", name := "X" }], membBody))
    (h_rm : w.defs.get? { package := "ACL2", name := "RM" }
      = some ([{ package := "ACL2", name := "E" },
               { package := "ACL2", name := "X" }], rmBody))
    (h_no_consp : w.defs.get? ({ name := "CONSP" } : Symbol) = none)
    (h_no_equal : w.defs.get? ({ name := "EQUAL" } : Symbol) = none)
    (h_no_car : w.defs.get? ({ name := "CAR" } : Symbol) = none)
    (h_no_cdr : w.defs.get? ({ name := "CDR" } : Symbol) = none)
    (h_no_cons : w.defs.get? ({ name := "CONS" } : Symbol) = none) :
    ∀ (env : Env) (a b av bv : SExpr),
      ConvTo w env a av → ConvTo w env b bv →
      ConvTo w env (pceT a b) (pceExec av bv) := by
  have hbody : ∀ xv yv : SExpr,
      ConvTo w (bindArgs [xS, yS] [xv, yv]) pceBody (pceExec xv yv) := by
    refine consCount_strong_induction
      (fun xv => ∀ yv, ConvTo w (bindArgs [xS, yS] [xv, yv]) pceBody
        (pceExec xv yv)) ?_
    intro xv ih yv
    have hxv := re_val_var_get w (bindArgs [xS, yS] [xv, yv])
      { name := "X" } xv (bindArgs_xy_x' xv yv)
    have hyv := re_val_var_get w (bindArgs [xS, yS] [xv, yv])
      { name := "Y" } yv (bindArgs_xy_y' xv yv)
    have hconsp := conv_builtin1 w _ { name := "CONSP" } xT xv
      (Logic.consp xv) (by decide) h_no_consp hxv (callBuiltin_consp _)
    have hcarx := conv_builtin1 w _ { name := "CAR" } xT xv
      (Logic.car xv) (by decide) h_no_car hxv (callBuiltin_car _)
    have hcary := conv_builtin1 w _ { name := "CAR" } yT yv
      (Logic.car yv) (by decide) h_no_car hyv (callBuiltin_car _)
    have hcdrx := conv_builtin1 w _ { name := "CDR" } xT xv
      (Logic.cdr xv) (by decide) h_no_cdr hxv (callBuiltin_cdr _)
    have hmemb := memb_exec_corr w h_memb h_no_consp h_no_equal h_no_car
      h_no_cdr _ (carT xT) yT (Logic.car xv) yv hcarx hyv
    have hrm := rm_exec_corr w h_rm h_no_consp h_no_equal h_no_car
      h_no_cdr h_no_cons _ (carT xT) yT (Logic.car xv) yv hcarx hyv
    have houter := conv_if_lift w (bindArgs [xS, yS] [xv, yv]) (conspT xT)
      (ifT (membT (carT xT) yT)
        (pceT (cdrT xT) (rmT (carT xT) yT))
        (carT xT))
      (carT yT) (Logic.consp xv)
      (if Logic.toBool (membExec (Logic.car xv) yv) = true then
        pceExec (Logic.cdr xv) (rmExec (Logic.car xv) yv)
       else Logic.car xv)
      (Logic.car yv) hconsp
      (fun hb =>
        conv_if_lift w _ (membT (carT xT) yT)
          (pceT (cdrT xT) (rmT (carT xT) yT)) (carT xT)
          (membExec (Logic.car xv) yv)
          (pceExec (Logic.cdr xv) (rmExec (Logic.car xv) yv))
          (Logic.car xv) hmemb
          (fun _ =>
            conv_defn_2 w _ pce_sym (cdrT xT) (rmT (carT xT) yT)
              (Logic.cdr xv) (rmExec (Logic.car xv) yv) xS yS pceBody _
              pce_ns h_pce hcdrx hrm
              (ih (Logic.cdr xv) (consCount_cdr_lt_of_consp hb)
                (rmExec (Logic.car xv) yv)))
          (fun _ => hcarx))
      (fun _ => hcary)
    rw [pceExec.eq_def]
    exact houter
  intro env a b av bv ha hb
  exact conv_defn_2 w env pce_sym a b av bv xS yS pceBody _
    pce_ns h_pce ha hb (hbody av bv)

/-! ## ORDEREDP-QSORT — the generic orderedp exec (arbitrary values,
where `corr_chain2_enc` is enc-only) + the in-book rule discharger. -/

/-- `orderedp`'s body as a total Lean function (the chain2 shape). -/
def orderedpExec (x : SExpr) : SExpr :=
  if Logic.toBool (Logic.consp x) = true then
    if Logic.toBool (Logic.consp (Logic.cdr x)) = true then
      if Logic.toBool (lexorder (Logic.car x) (Logic.car (Logic.cdr x)))
          = true then
        orderedpExec (Logic.cdr x)
      else SExpr.nil
    else SExpr.t
  else SExpr.t
termination_by x.consCount
decreasing_by exact consCount_cdr_lt_of_consp (by assumption)

theorem orderedpExec_t_or_nil (x : SExpr) :
    orderedpExec x = SExpr.t ∨ orderedpExec x = SExpr.nil := by
  fun_induction orderedpExec x with
  | case1 x _ _ _ ih => exact ih
  | case2 x _ _ _ => exact Or.inr rfl
  | case3 x _ _ => exact Or.inl rfl
  | case4 x _ => exact Or.inl rfl

private theorem orderedp_ns :
    (orderedp_sym.isNamed "QUOTE" = false ∧
     orderedp_sym.isNamed "IF" = false ∧
     orderedp_sym.isNamed "LET" = false ∧
     orderedp_sym.isNamed "LET*" = false) := by decide

/-- Stage 1: an `orderedp` call converges to `orderedpExec` (over
    ARBITRARY values). -/
theorem orderedp_exec_corr (w : World)
    (h_ord : w.defs.get? orderedp_sym
      = some ([{ package := "ACL2", name := "X" }],
              chain2Body "LEXORDER" "ORDEREDP"))
    (h_no_consp : w.defs.get? ({ name := "CONSP" } : Symbol) = none)
    (h_no_car : w.defs.get? ({ name := "CAR" } : Symbol) = none)
    (h_no_cdr : w.defs.get? ({ name := "CDR" } : Symbol) = none)
    (h_no_lexorder : w.defs.get? ({ name := "LEXORDER" } : Symbol) = none) :
    ∀ (env : Env) (x xv : SExpr),
      ConvTo w env x xv → ConvTo w env (orderedpT x) (orderedpExec xv)
    := by
  have hbody : ∀ xv : SExpr,
      ConvTo w (bindArgs [xS] [xv]) (chain2Body "LEXORDER" "ORDEREDP")
        (orderedpExec xv) := by
    refine consCount_strong_induction
      (fun xv => ConvTo w (bindArgs [xS] [xv])
        (chain2Body "LEXORDER" "ORDEREDP") (orderedpExec xv)) ?_
    intro xv ih
    have hxv := re_val_var_get w (bindArgs [xS] [xv]) { name := "X" } xv
      (bindArgs_single_get_self xS xv)
    have hconsp := conv_builtin1 w _ { name := "CONSP" } xT xv
      (Logic.consp xv) (by decide) h_no_consp hxv (callBuiltin_consp _)
    have hcar := conv_builtin1 w _ { name := "CAR" } xT xv
      (Logic.car xv) (by decide) h_no_car hxv (callBuiltin_car _)
    have hcdr := conv_builtin1 w _ { name := "CDR" } xT xv
      (Logic.cdr xv) (by decide) h_no_cdr hxv (callBuiltin_cdr _)
    have hconsp2 := conv_builtin1 w _ { name := "CONSP" } (cdrT xT)
      (Logic.cdr xv) (Logic.consp (Logic.cdr xv)) (by decide) h_no_consp
      hcdr (callBuiltin_consp _)
    have hcadr := conv_builtin1 w _ { name := "CAR" } (cdrT xT)
      (Logic.cdr xv) (Logic.car (Logic.cdr xv)) (by decide) h_no_car hcdr
      (callBuiltin_car _)
    have hlex := conv_builtin2 w _ { name := "LEXORDER" } (carT xT)
      (carT (cdrT xT)) (Logic.car xv) (Logic.car (Logic.cdr xv)) _
      (by decide) h_no_lexorder hcar hcadr (callBuiltin_lexorder _ _)
    have houter := conv_if_lift w (bindArgs [xS] [xv]) (conspT xT)
      (ifT (conspT (cdrT xT))
        (ifT (lexT (carT xT) (carT (cdrT xT)))
          (app1 "ORDEREDP" (cdrT xT)) qNil)
        qT')
      qT' (Logic.consp xv)
      (if Logic.toBool (Logic.consp (Logic.cdr xv)) = true then
        (if Logic.toBool (lexorder (Logic.car xv)
            (Logic.car (Logic.cdr xv))) = true then
          orderedpExec (Logic.cdr xv)
         else SExpr.nil)
       else SExpr.t)
      SExpr.t hconsp
      (fun hb =>
        conv_if_lift w _ (conspT (cdrT xT)) _ qT'
          (Logic.consp (Logic.cdr xv))
          (if Logic.toBool (lexorder (Logic.car xv)
              (Logic.car (Logic.cdr xv))) = true then
            orderedpExec (Logic.cdr xv)
           else SExpr.nil)
          SExpr.t hconsp2
          (fun _ =>
            conv_if_lift w _ (lexT (carT xT) (carT (cdrT xT)))
              (app1 "ORDEREDP" (cdrT xT)) qNil
              (lexorder (Logic.car xv) (Logic.car (Logic.cdr xv)))
              (orderedpExec (Logic.cdr xv)) SExpr.nil hlex
              (fun _ =>
                conv_defn_1 w _ orderedp_sym (cdrT xT) (Logic.cdr xv)
                  { package := "ACL2", name := "X" }
                  (chain2Body "LEXORDER" "ORDEREDP") _ orderedp_ns h_ord
                  hcdr
                  (ih (Logic.cdr xv) (consCount_cdr_lt_of_consp hb)))
              (fun _ => re_val_quote w _ SExpr.nil))
          (fun _ => re_val_quote w _ SExpr.t))
      (fun _ => re_val_quote w _ SExpr.t)
    rw [orderedpExec.eq_def]
    exact houter
  intro env x xv hx
  exact conv_defn_1 w env orderedp_sym x xv
    { package := "ACL2", name := "X" } (chain2Body "LEXORDER" "ORDEREDP")
    _ orderedp_ns h_ord hx (hbody xv)

theorem bnext_ns :
    (bnext_sym.isNamed "QUOTE" = false ∧ bnext_sym.isNamed "IF" = false ∧
     bnext_sym.isNamed "LET" = false ∧
     bnext_sym.isNamed "LET*" = false) := by decide

/-- The swap-site decrease: replacing the two-element head prefix by the
    (single) first element strictly drops `consCount`. -/
theorem consCount_bnext_swap_lt {x : SExpr}
    (h1 : Logic.toBool (Logic.consp x) = true)
    (h2 : Logic.toBool (Logic.consp (Logic.cdr x)) = true) :
    (Logic.cons (Logic.car x) (Logic.cdr (Logic.cdr x))).consCount
      < x.consCount := by
  match x with
  | .cons a d =>
    match d with
    | .cons b d' =>
      simp only [Logic.car, Logic.cdr, Logic.cons, consCount_cons]
      omega
    | .atom _ => simp [Logic.cdr, Logic.consp, Logic.toBool] at h2
    | .nil => simp [Logic.cdr, Logic.consp, Logic.toBool] at h2
  | .atom _ => simp [Logic.consp, Logic.toBool] at h1
  | .nil => simp [Logic.consp, Logic.toBool] at h1

/-- `bnext`'s body as a total Lean function. -/
def bnextExec (x : SExpr) : SExpr :=
  if _h1 : Logic.toBool (Logic.consp x) = true then
    if _h2 : Logic.toBool (Logic.consp (Logic.cdr x)) = true then
      if Logic.toBool (lexorder (Logic.car x) (Logic.car (Logic.cdr x)))
          = true then
        Logic.cons (Logic.car x) (bnextExec (Logic.cdr x))
      else
        Logic.cons (Logic.car (Logic.cdr x))
          (bnextExec (Logic.cons (Logic.car x) (Logic.cdr (Logic.cdr x))))
    else x
  else x
termination_by x.consCount
decreasing_by
  all_goals first
    | exact consCount_cdr_lt_of_consp _h1
    | exact consCount_bnext_swap_lt _h1 _h2

register_exec_kit% "BNEXT" => bnextExec arity 1

/-- Stage 2: `bnextExec` on an encoded list computes the native bubble
    pass — GENERATED (hand exec: the CONS-argument recursion site is
    beyond `derive_exec%`, but the ISO is on the template). -/
derive_sim% bnextExec_enc for "BNEXT"
  vars (xs : list)
  exec [xs]
  native (enc (bnextL xs))
  simp [bnextL, lexorder_eq_boolEnc]
  induct functional (bnextL xs)

/-- Stage 1: a `bnext` call converges to `bnextExec`. -/
theorem bnext_exec_corr (w : World)
    (h_bnext : w.defs.get? bnext_sym = some ([xS], bnextBody))
    (h_no_consp : w.defs.get? ({ name := "CONSP" } : Symbol) = none)
    (h_no_car : w.defs.get? ({ name := "CAR" } : Symbol) = none)
    (h_no_cdr : w.defs.get? ({ name := "CDR" } : Symbol) = none)
    (h_no_cons : w.defs.get? ({ name := "CONS" } : Symbol) = none)
    (h_no_lexorder : w.defs.get? ({ name := "LEXORDER" } : Symbol) = none) :
    ∀ (env : Env) (x xv : SExpr),
      ConvTo w env x xv → ConvTo w env (app1 "BNEXT" x) (bnextExec xv) := by
  have hbody : ∀ xv : SExpr,
      ConvTo w (bindArgs [xS] [xv]) bnextBody (bnextExec xv) := by
    refine consCount_strong_induction
      (fun xv => ConvTo w (bindArgs [xS] [xv]) bnextBody (bnextExec xv)) ?_
    intro xv ih
    have hxv := re_val_var_get w (bindArgs [xS] [xv]) { name := "X" } xv
      (bindArgs_single_get_self xS xv)
    have hconsp := conv_builtin1 w _ { name := "CONSP" } xT xv
      (Logic.consp xv) (by decide) h_no_consp hxv (callBuiltin_consp _)
    have hcar := conv_builtin1 w _ { name := "CAR" } xT xv
      (Logic.car xv) (by decide) h_no_car hxv (callBuiltin_car _)
    have hcdr := conv_builtin1 w _ { name := "CDR" } xT xv
      (Logic.cdr xv) (by decide) h_no_cdr hxv (callBuiltin_cdr _)
    have hconsp2 := conv_builtin1 w _ { name := "CONSP" } (cdrT xT)
      (Logic.cdr xv) (Logic.consp (Logic.cdr xv)) (by decide) h_no_consp
      hcdr (callBuiltin_consp _)
    have hcar2 := conv_builtin1 w _ { name := "CAR" } (cdrT xT)
      (Logic.cdr xv) (Logic.car (Logic.cdr xv)) (by decide) h_no_car
      hcdr (callBuiltin_car _)
    have hcddr := conv_builtin1 w _ { name := "CDR" } (cdrT xT)
      (Logic.cdr xv) (Logic.cdr (Logic.cdr xv)) (by decide) h_no_cdr
      hcdr (callBuiltin_cdr _)
    have hlex := conv_builtin2 w _ { name := "LEXORDER" } (carT xT)
      (carT (cdrT xT)) (Logic.car xv) (Logic.car (Logic.cdr xv)) _
      (by decide) h_no_lexorder hcar hcar2 (callBuiltin_lexorder _ _)
    have hkeep : Logic.toBool (Logic.consp xv) = true →
        ConvTo w (bindArgs [xS] [xv])
          (consT (carT xT) (app1 "BNEXT" (cdrT xT)))
          (Logic.cons (Logic.car xv) (bnextExec (Logic.cdr xv))) := by
      intro hb1
      exact conv_builtin2 w _ { name := "CONS" } (carT xT)
        (app1 "BNEXT" (cdrT xT)) (Logic.car xv)
        (bnextExec (Logic.cdr xv)) _ (by decide) h_no_cons hcar
        (conv_defn_1 w _ bnext_sym (cdrT xT) (Logic.cdr xv) xS bnextBody _
          bnext_ns h_bnext hcdr
          (ih (Logic.cdr xv) (consCount_cdr_lt_of_consp hb1))) rfl
    have hswap : Logic.toBool (Logic.consp xv) = true →
        Logic.toBool (Logic.consp (Logic.cdr xv)) = true →
        ConvTo w (bindArgs [xS] [xv])
          (consT (carT (cdrT xT))
            (app1 "BNEXT" (consT (carT xT) (cdrT (cdrT xT)))))
          (Logic.cons (Logic.car (Logic.cdr xv))
            (bnextExec (Logic.cons (Logic.car xv)
              (Logic.cdr (Logic.cdr xv))))) := by
      intro hb1 hb2
      have hArg := conv_builtin2 w _ { name := "CONS" } (carT xT)
        (cdrT (cdrT xT)) (Logic.car xv) (Logic.cdr (Logic.cdr xv)) _
        (by decide) h_no_cons hcar hcddr rfl
      exact conv_builtin2 w _ { name := "CONS" } (carT (cdrT xT))
        (app1 "BNEXT" (consT (carT xT) (cdrT (cdrT xT))))
        (Logic.car (Logic.cdr xv))
        (bnextExec (Logic.cons (Logic.car xv) (Logic.cdr (Logic.cdr xv))))
        _ (by decide) h_no_cons hcar2
        (conv_defn_1 w _ bnext_sym (consT (carT xT) (cdrT (cdrT xT)))
          (Logic.cons (Logic.car xv) (Logic.cdr (Logic.cdr xv))) xS
          bnextBody _ bnext_ns h_bnext hArg
          (ih (Logic.cons (Logic.car xv) (Logic.cdr (Logic.cdr xv)))
            (consCount_bnext_swap_lt hb1 hb2))) rfl
    have houter := conv_if_lift w (bindArgs [xS] [xv]) (conspT xT)
      (ifT (conspT (cdrT xT))
        (ifT (lexT (carT xT) (carT (cdrT xT)))
          (consT (carT xT) (app1 "BNEXT" (cdrT xT)))
          (consT (carT (cdrT xT))
            (app1 "BNEXT" (consT (carT xT) (cdrT (cdrT xT))))))
        xT)
      xT (Logic.consp xv)
      (if Logic.toBool (Logic.consp (Logic.cdr xv)) = true then
        (if Logic.toBool (lexorder (Logic.car xv)
            (Logic.car (Logic.cdr xv))) = true then
          Logic.cons (Logic.car xv) (bnextExec (Logic.cdr xv))
        else
          Logic.cons (Logic.car (Logic.cdr xv))
            (bnextExec (Logic.cons (Logic.car xv)
              (Logic.cdr (Logic.cdr xv)))))
       else xv)
      xv hconsp
      (fun hb1 =>
        conv_if_lift w _ (conspT (cdrT xT))
          (ifT (lexT (carT xT) (carT (cdrT xT)))
            (consT (carT xT) (app1 "BNEXT" (cdrT xT)))
            (consT (carT (cdrT xT))
              (app1 "BNEXT" (consT (carT xT) (cdrT (cdrT xT))))))
          xT (Logic.consp (Logic.cdr xv))
          (if Logic.toBool (lexorder (Logic.car xv)
              (Logic.car (Logic.cdr xv))) = true then
            Logic.cons (Logic.car xv) (bnextExec (Logic.cdr xv))
          else
            Logic.cons (Logic.car (Logic.cdr xv))
              (bnextExec (Logic.cons (Logic.car xv)
                (Logic.cdr (Logic.cdr xv)))))
          xv hconsp2
          (fun hb2 =>
            conv_if_lift w _ (lexT (carT xT) (carT (cdrT xT)))
              (consT (carT xT) (app1 "BNEXT" (cdrT xT)))
              (consT (carT (cdrT xT))
                (app1 "BNEXT" (consT (carT xT) (cdrT (cdrT xT)))))
              (lexorder (Logic.car xv) (Logic.car (Logic.cdr xv)))
              (Logic.cons (Logic.car xv) (bnextExec (Logic.cdr xv)))
              (Logic.cons (Logic.car (Logic.cdr xv))
                (bnextExec (Logic.cons (Logic.car xv)
                  (Logic.cdr (Logic.cdr xv)))))
              hlex
              (fun _ => hkeep hb1) (fun _ => hswap hb1 hb2))
          (fun _ => hxv))
      (fun _ => hxv)
    rw [bnextExec.eq_def]
    simp only [dite_eq_ite] at *
    exact houter
  intro env x xv hx
  exact conv_defn_1 w env bnext_sym x xv xS bnextBody _
    bnext_ns h_bnext hx (hbody xv)

end ACL2.Worlds.Sorting
