import ACL2Lean.MirrorProofs.SortingPermSquares
import ACL2Lean.Imported.SortingBsortKit

/-! # W14 — `bsort`'s TWO SQUARES (R4 wave 2g)

The last definition on the sorting witness page to get both squares, and
the one that needed a template CAPABILITY rather than a rung.

**What was blocking them, and what moved.** Wave 2b recorded both as
frontiers on an ACCESS-PATTERN mismatch (the spec rendered BSORT as
`length`-many `foldl` passes while the book recurses to the fixed point);
ruling Q2 removed that in wave 2d-prep by re-rendering the spec as the
book's own fixpoint recursion. Two new blockers were then measured and
recorded verbatim on `MirrorProofs/SortingSquares.lean`'s W14 postscript:

* the AGREE square had NO READING — there was no `bsortL`, because there
  was no BSORT exec kit. `Imported/SortingBsortKit.lean` is that kit, and
  it is generated by `derive_exec%`'s `userFn` measure row;
* BOTH squares hit a LOOPING CLOSER (`Possibly looping simp theorem:
  Sorting.bsort.eq_1`, then a `whnf` timeout) — a fixpoint recursion's
  own equation rewrites its own recursive call forever.

The second is what the FIXPOINT-GUARD capability closes
(`MirrorProofs/IsoKit.lean`): the closer is handed the definition's TWO
GUARDED equations instead of its unconditional one. The capability is
read off the definition and fires only on that shape, so no
pre-existing square's script or proof term changes.

Both squares are `#guard_msgs`-pinned below and both are trio-clean.
Their consumers are the two products in `MirrorProofs/Sorting.lean`. -/

namespace ACL2Lean.MirrorProofs

open ACL2 ACL2Lean

/-- W14 AGREE — the spec's `bsort` IS the kit's `bsortL`. Closes off the
    guarded equations of BOTH fixpoints plus the registered `bnext` agree
    square; without that square the guard cannot cross into the reading's
    vocabulary at all. -/
mirror_iso% bsort_agree_bsortL for ACL2Lean.Sorting.bsort
  vars [xs]
  square agree (Worlds.Sorting.bsortL xs)
  unfold [Worlds.Sorting.bsortL]

/-- info: 'ACL2Lean.MirrorProofs.bsort_agree_bsortL' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms bsort_agree_bsortL

/-- W14 HOM — `bsort` commutes with an ORDER-RESPECTING embedding. The
    order-respect is load-bearing through `bnext`'s own hom square, and
    the guard is carried across the embedding by that square (reversed)
    plus `map_inj_iff`. -/
mirror_iso% bsort_map_hom for ACL2Lean.Sorting.bsort
  vars [xs]
  square hom list
  embed OrderedEmbed via [ord]

/-- info: 'ACL2Lean.MirrorProofs.bsort_map_hom' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms bsort_map_hom

end ACL2Lean.MirrorProofs
