import ACL2Lean.Imported.Waypoints.Bsort

/-! # Imported: the BSORT KIT — the corpus's `userFn`-measured defun

`(defun bsort (x) (if (equal (bnext x) x) x (bsort (bnext x))))`, measured
by `(BNEXT-SIZE X)`. It is the witness of `derive_exec%`'s `userFn`
MEASURE ROW (R4 wave 2g, `Imported/ExecGen.lean`'s header): a defun that
recurses to a FIXED POINT under a world-function measure rather than down
a destructor chain.

**Why this module sits ABOVE the waypoint layer, unlike every other
kit.** The generated exec's termination proof IS a replayed theorem
(`how_many_bad_pairs_bnext_exec_driver`, the book's
HOW-MANY-BAD-PAIRS-BNEXT), so the kit cannot be built below the module
that replays it. The same is true of the native reading `bsortL`. That
inverts the usual layering for this one book and is the honest shape of
the row: ACL2 admits `BSORT` only because it has already proved that
lemma, and so do we.

Nothing here re-proves an ACL2 theorem. The two `NatValued` facts
(`Imported/SortingBsort.lean`) are about our own generated execs, and
everything else is generated or decodes a replayed statement. -/

open ACL2 ACL2.Replay ACL2.Lifting ACL2.ExecGen ACL2.Imported.Waypoints

namespace ACL2.Worlds.Sorting

/-! ## The generated kit -/

/-! BNEXT's kit is HAND-WRITTEN (its CONS-argument recursion site is
beyond `derive_exec%`), and BSORT's GENERATED corr calls it — the first
time a generated corr needs a hand callee, which is exactly the case
`register_exec_corr%` exists for. -/
register_exec_corr% "BNEXT" => bnext_exec_corr for bnext_sym
  formals [xS] body bnextBody

def bsort_sym : Symbol := { package := "ACL2", name := "BSORT" }

/-- `(defun bsort (x) …)`, macroexpanded — bubble passes to the fixed
    point. -/
def bsortBody : SExpr :=
  appIf (equalT (app1 "BNEXT" xT) xT) xT (app1 "BSORT" (app1 "BNEXT" xT))

/-- `bsort`'s body as a total Lean function + its stage-1 corr —
    GENERATED by the `userFn` measure row. `via "BNEXT-SIZE"` names the
    emitted `:MEASURE`'s head (its exec is the measure) and `decreasing`
    names the REPLAYED decrease; nothing about bubble sort is built in. -/
derive_exec% bsortExec corr bsort_exec_corr for bsort_sym
  formals [xS] body bsortBody
  measured 0 via "BNEXT-SIZE" decreasing how_many_bad_pairs_bnext_exec_driver

/-! ## The native reading -/

/-- The NATIVE bubble sort: bubble passes until one changes nothing.
    ORDINARY Lean definition — its termination is the REPLAYED decrease
    (`how_many_bad_pairs_bnext_native_driver`), so there is no hand
    termination proof here either. -/
def bsortL (xs : List SExpr) : List SExpr :=
  if bnextL xs = xs then xs else bsortL (bnextL xs)
termination_by bnextSizeL xs
decreasing_by
  exact how_many_bad_pairs_bnext_native_driver xs (Ne.symm (by assumption))

/-- `bsortL`'s own equation under the FIXED-POINT guard. -/
theorem bsortL_fix {xs : List SExpr} (h : bnextL xs = xs) : bsortL xs = xs := by
  rw [bsortL]; simp [h]

/-- `bsortL`'s own equation under the PROGRESS guard. -/
theorem bsortL_step {xs : List SExpr} (h : ¬ bnextL xs = xs) :
    bsortL xs = bsortL (bnextL xs) := by
  rw [bsortL]; simp [h]

/-- `enc`'s injectivity at the `Bool` equality test — what the iso's
    fixed-point TEST needs (the `enc_inj` of `Imported/Lifting.lean`, read
    through `==`). -/
theorem enc_beq (a b : List SExpr) : (enc a == enc b) = (a == b) := by
  by_cases h : a = b
  · subst h; simp
  · have hne : ¬ (enc a = enc b) := fun he => h (enc_inj he)
    simp [h, hne]

/-- Stage 2: `bsortExec` on an encoded list computes `bsortL` —
    GENERATED; the BNEXT callee iso resolves through the kit registry and
    `enc_beq` carries the fixed-point test across `enc`. -/
derive_sim% bsortExec_enc for "BSORT"
  vars (xs : list)
  exec [xs]
  native (enc (bsortL xs))
  simp [enc_beq]
  induct functional (bsortL xs)

/-! ## ORDEREDP-BSORT -/

abbrev bsortT (x : SExpr) : SExpr := app1 "BSORT" x

/-- The ORDEREDP-BSORT replayed-statement formula — the root Goal clause,
    exactly as the log emits it: `(ORDEREDP (BSORT X))`. -/
def orderedp_bsortFormula : SExpr := orderedpT (bsortT xT)

/-- ORDEREDP-BSORT, natively: BUBBLE SORT ALWAYS SORTS.
    SCOPE: the native quantifies over `List SExpr` — the `enc` IMAGE —
    while the ACL2 theorem is over ALL objects, so this is strictly
    WEAKER than the replayed statement (the standing type-absorbed
    doctrine). -/
theorem orderedp_bsort_native_of_replayed (w : World)
    (h_orderedp : w.defs.get? { package := "ACL2", name := "ORDEREDP" }
      = some ([{ package := "ACL2", name := "X" }],
              chain2Body "LEXORDER" "ORDEREDP"))
    (h_bnext : w.defs.get? bnext_sym = some ([xS], bnextBody))
    (h_bsort : w.defs.get? bsort_sym = some ([xS], bsortBody))
    (h_no_consp : w.defs.get? ({ name := "CONSP" } : Symbol) = none)
    (h_no_equal : w.defs.get? ({ name := "EQUAL" } : Symbol) = none)
    (h_no_car : w.defs.get? ({ name := "CAR" } : Symbol) = none)
    (h_no_cdr : w.defs.get? ({ name := "CDR" } : Symbol) = none)
    (h_no_cons : w.defs.get? ({ name := "CONS" } : Symbol) = none)
    (h_no_lexorder : w.defs.get? ({ name := "LEXORDER" } : Symbol) = none)
    (hreplayed : ∀ env : Env, ∃ N, ∀ f, f ≥ N → ∃ v,
      evalOpt f w env orderedp_bsortFormula = some v ∧ v ≠ SExpr.nil)
    (xs : List SExpr) :
    orderedpRec (bsortL xs) = true := by
  let e : Env := ({} : Env).insert xS (enc xs)
  have hx : ∃ N, ∀ f ≥ N, evalOpt f w e xT = some (enc xs) :=
    re_val_var_get w e { name := "X" } (enc xs) (by
      show e.get? xS = some (enc xs)
      rw [show e = ({} : Env).insert xS (enc xs) from rfl,
          Env.get?_insert, if_pos (by decide)])
  have hbs := bsort_exec_corr w h_bnext h_bsort h_no_consp h_no_equal
    h_no_car h_no_cdr h_no_cons h_no_lexorder e xT (enc xs) hx
  rw [bsortExec_enc] at hbs
  have hord := corr_orderedp_enc w h_orderedp h_no_consp h_no_cdr h_no_car
    h_no_lexorder (bsortL xs) e (bsortT xT) hbs
  exact bool_true_of_cond_truthy (toBool_true_of_ne_nil
    (replayed_pins_ne_nil (hreplayed e) hord))

/-! ## HOW-MANY-BSORT -/

/-- The HOW-MANY-BSORT replayed-statement formula — the root Goal clause,
    exactly as the log emits it:
    `(EQUAL (HOW-MANY E (BSORT X)) (HOW-MANY E X))`. -/
def how_many_bsortFormula : SExpr :=
  equalT (howManyT eT (bsortT xT)) (howManyT eT xT)

/-- HOW-MANY-BSORT, natively: BUBBLE SORT PRESERVES MULTIPLICITY.
    SCOPE: the native quantifies over `List SExpr` — the `enc` IMAGE —
    while the ACL2 theorem is over ALL objects, so this is strictly
    WEAKER than the replayed statement (the standing type-absorbed
    doctrine). -/
theorem how_many_bsort_native_of_replayed (w : World)
    (h_hm : w.defs.get? how_many_sym = some ([eS, xS], howManyBody))
    (h_bnext : w.defs.get? bnext_sym = some ([xS], bnextBody))
    (h_bsort : w.defs.get? bsort_sym = some ([xS], bsortBody))
    (h_no_consp : w.defs.get? ({ name := "CONSP" } : Symbol) = none)
    (h_no_equal : w.defs.get? ({ name := "EQUAL" } : Symbol) = none)
    (h_no_car : w.defs.get? ({ name := "CAR" } : Symbol) = none)
    (h_no_cdr : w.defs.get? ({ name := "CDR" } : Symbol) = none)
    (h_no_cons : w.defs.get? ({ name := "CONS" } : Symbol) = none)
    (h_no_lexorder : w.defs.get? ({ name := "LEXORDER" } : Symbol) = none)
    (h_no_plus : w.defs.get? ({ name := "BINARY-+" } : Symbol) = none)
    (hreplayed : ∀ env : Env, ∃ N, ∀ f, f ≥ N → ∃ v,
      evalOpt f w env how_many_bsortFormula = some v ∧ v ≠ SExpr.nil)
    (ev : SExpr) (xs : List SExpr) :
    howManyL ev (bsortL xs) = howManyL ev xs := by
  let e : Env := (({} : Env).insert xS (enc xs)).insert eS ev
  have he : ∃ N, ∀ f ≥ N, evalOpt f w e eT = some ev :=
    re_val_var_get w e { name := "E" } ev (by
      show e.get? eS = some ev
      rw [show e = (({} : Env).insert xS (enc xs)).insert eS ev from rfl,
          Env.get?_insert, if_pos (by decide)])
  have hx : ∃ N, ∀ f ≥ N, evalOpt f w e xT = some (enc xs) :=
    re_val_var_get w e { name := "X" } (enc xs) (by
      show e.get? xS = some (enc xs)
      rw [show e = (({} : Env).insert xS (enc xs)).insert eS ev from rfl,
          Env.get?_insert, if_neg (by decide), Env.get?_insert,
          if_pos (by decide)])
  have hbs := bsort_exec_corr w h_bnext h_bsort h_no_consp h_no_equal
    h_no_car h_no_cdr h_no_cons h_no_lexorder e xT (enc xs) hx
  rw [bsortExec_enc] at hbs
  have hL := how_many_exec_corr w h_hm h_no_consp h_no_equal h_no_car
    h_no_cdr h_no_plus e eT (bsortT xT) ev (enc (bsortL xs)) he hbs
  rw [howManyExec_enc] at hL
  have hR := how_many_exec_corr w h_hm h_no_consp h_no_equal h_no_car
    h_no_cdr h_no_plus e eT xT ev (enc xs) he hx
  rw [howManyExec_enc] at hR
  have hnat := native_of_replayed_equal w e intRep _ _
    (howManyL ev (bsortL xs)) (howManyL ev xs) h_no_equal hL hR (hreplayed e)
  omega

end ACL2.Worlds.Sorting
